version: '3'
services:  
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
    
    
  postgres:
    image: postgres:13-alpine
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=letterbox
      - POSTGRES_USER=letterbox
      - POSTGRES_PASSWORD=letterbox
    
