# Generated by Django 4.0.6 on 2022-07-17 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mails', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='emailbalance',
            name='settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mails.emailsettings'),
        ),
    ]
