# Generated by Django 4.0.6 on 2022-07-17 13:42

from django.db import migrations, models
import django.db.models.deletion
import letterbox.fields
import newsletter.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', letterbox.fields.IdentifierField(help_text='internal name', max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', letterbox.fields.IdentifierField(default=newsletter.models.generate_name_nl, help_text='internal name', max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semester', 'Semester'), ('yearly', 'Yearly'), ('other', 'Other')], default='other', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('newsletter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
