# Generated by Django 4.0.6 on 2022-07-17 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('newsletter', '0001_initial'),
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='users.company'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='genres',
            field=models.ManyToManyField(blank=True, to='newsletter.genre'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='letters',
            field=models.ManyToManyField(blank=True, through='newsletter.NewsletterCampaign', to='campaigns.campaign'),
        ),
        migrations.AlterUniqueTogether(
            name='newsletter',
            unique_together={('company', 'title')},
        ),
    ]
