# Generated by Django 3.1 on 2021-12-13 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsletter', '0001_initial'),
        ('campaigns', '0002_campaign_company'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='users.company'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='genres',
            field=models.ManyToManyField(blank=True, to='newsletter.Genre'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='letters',
            field=models.ManyToManyField(through='newsletter.NewsletterCampaign', to='campaigns.Campaign'),
        ),
        migrations.AlterUniqueTogether(
            name='newsletter',
            unique_together={('company', 'title')},
        ),
    ]
