# Generated by Django 3.1 on 2021-12-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_company'),
        ('newsletter', '0002_auto_20211213_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='letters',
            field=models.ManyToManyField(blank=True, through='newsletter.NewsletterCampaign', to='campaigns.Campaign'),
        ),
    ]
