# Generated by Django 4.0.6 on 2022-07-23 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_rename_name_campaign_identifier'),
        ('newsletter', '0003_rename_name_genre_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettercampaign',
            name='letter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='newslettercampaign',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletter'),
        ),
    ]
