# Generated by Django 4.0.6 on 2022-07-29 17:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0004_alter_subscriber_email_alter_tag_title'),
        ('newsletter', '0004_alter_newslettercampaign_letter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subscribers',
            field=models.ManyToManyField(blank=True, through='newsletter.NewsletterSubscriber', to='subscribers.subscriber'),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletter'),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='subscriber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subscribers.subscriber'),
        ),
    ]
