# Generated by Django 4.0.6 on 2022-07-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_rename_name_campaign_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncontent',
            name='content_type',
            field=models.CharField(choices=[('title', 'Title'), ('paragraph', 'Paragraph'), ('single_img', 'Single Image'), ('multiple_img', 'Multiple Image'), ('content_img', 'Content with Image'), ('navigation', 'Navigation'), ('space', 'Space'), ('divider', 'Divider'), ('social_links', 'Social Links'), ('button', 'Button'), ('html', 'HTML')], max_length=20),
        ),
        migrations.AlterField(
            model_name='campaigncontent',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
