# Generated by Django 4.0.6 on 2022-07-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaigncontent_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncontent',
            name='text',
            field=models.TextField(default='', null=True),
        ),
    ]
