# Generated by Django 4.0.6 on 2022-07-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='identifier',
        ),
    ]
