# Generated by Django 4.0.6 on 2022-07-29 17:46

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_rename_name_tag_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True),
        ),
    ]
